### ISSUE TITLE
Calls from external sources (web browser)

### ISSUE THREAD

**Issue by jgato** [circuit/circuit.github.io#1]
Sorry if this is not the right place to make this questions. I am using circuit and we have phone call services. So, it would be really helpful to make calls just clicking on a phone number in a web browser. The browser detects phonenumbers in a webpage and provides links to Circuit calls. Is there something like an url/uri to make calls with circuit?

**Comment by rogeru** [comment]
Hi @jgato, how does your browser detect the phone numbers? Did you write a Chrome Extension, or install an extension that recognizes the phone numbers?

circuit currently supports the url https://eu.yourcircuit.com/phone?number=15615551234 which opens the phone calls conversation with that number prefilled, but does not initiate the call. We are planning on adding the capability to automatically initiate the call with a route such as https://eu.yourcircuit.com/phone?number=15615551234&dial=true. We are also planning to enhance the Circuit Extension to recognize phone numbers and provide exactly what you are asking for, which is to dial that number using circuit.

**Comment by jgato** [comment]
This kind of REST interface is perfect for these kind of ideas. I have tried this [url](https://eu.yourcircuit.com/phone?number=15615551234) but the response is

```
Cannot GET /phone?number=15615551234
```

But it this will work it will be perfect. I am looking some Firefox extensions to transform phonenumbers into link (customizable). I have tried some, but too related to specific services and dont let you try what to do with the link.

Please dont forget about Firefox and other browsers ;)

**Comment by jgato** [comment]
Ok, with [telify addon](https://addons.mozilla.org/en-US/firefox/addon/telify/?src=search) is pretty easy to get what we want (Firefox). 

You only have to configure the custom url mode of this addon:
![pic1](https://cloud.githubusercontent.com/assets/3435696/21430896/75d16376-c865-11e6-8977-aea50474b949.png)

This addon will detect phone number as links, this works pretty well for example with google contacts, or google search results. Cool. But even phone numbers are not automatically detected you can search any test, select it, and invoke the addon:

![pic2](https://cloud.githubusercontent.com/assets/3435696/21431054/13d882a2-c866-11e6-8dc9-37359b82798a.png)

Notice that you can try to call to any "phone-text". The addon tries to add automatically a postal code number, or you can edit to correct this. After that the custom url will be invoked as configured by the addon:

````
 https://eu.yourcircuit.com/phone?number=$0
```

But this url is not working ;)  It cannot be easier...

**Comment by rogeru** [comment]
Sorry, the url is hashbang url, e.g. 
```
https://eu.yourcircuit.com/#/phone?number=1561551234
```
And note that this is not a REST API, but a Circuit webclient route.

**Comment by jgato** [comment]
yeaaaaaaaah @rogeru now it worked like a charm!!! With Telify and the new custom url I can call from any (phone)-number, detected or not, in a webpage.

**Comment by jgato** [comment]
@rogeru I have created this [mini project](https://github.com/jgato/circuit-url-handler) as a tutorial with some scripts to get this working with Firefox/Thunderbird and GNU/Linux. How we could promote it? Do you think it could be interesting for others?

**Comment by rogeru** [comment]
Great work! I can add a "third-party projects using the Circuit SDK" sections on circuit.github.io and list this. But since we are planning to incorporate that into circuit directly (extension), I don't want to officially promote a workaround with a third-party FF extension.

Keep up to good work though!
