### ISSUE TITLE
"Getting started" has wrong instructions

### ISSUE THREAD

**Issue by DDimitris** [circuit/circuit.github.io#3]
In the "Setup your environment" section of the "Getting started" page, the second step has the following instructions:
```
In your sandbox, go to the "Administration" > "OAuth Apps" and create a new application.
Note that if you do not see this option, enable "OAuth Apps" in "Settings" > "Circuit Labs"
```

Currently, in case a user wants to create a new OAuth App, he/she needs to do the following: 

```
In your sandbox, go to the "Manage applications" > "Custom Apps" > hit "Create"
```
From there he/she can choose the type of app for creation

**Comment by rogeru** [comment]
Thanks @DDimitris you are correct.
